export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundColor: "black",
          color: "white",
        }}
      >
        <header
          style={{
            backgroundColor: "lightblue",
            padding: "1rem",
            color: "black"
          }}
        >
          <p>Header</p>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
            color: "black"
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
